apiVersion: v1
kind: pod
metadata:
  name: additional-service
  labels:
    name: additional-service
spec:
  containers:
  -name: additional-service
  image: aaqibjsregistry.azurecr.io/gs-spring-boot-docker:latest
  imagePullPolicy: "Always"
  ports:
  -containerPort: 80
